version: '3.6'
    
services: 
    webserver01:
        image: webserver01:latest
        container_name: webserver01
        build: ./web/.
        volumes:
          - ./user01/html:/usr/local/apache2/htdocs/
          - ./user01/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
          - 30001:80

    appserver01:
        image: appserver01:latest
        container_name: appserver01
        build: ./app/.
        depends_on:
          - webserver01
        environment:
          ctf_flag: juegoctf{nicelist_86815}
          key: 86815
        volumes:
          - ./user01/html:/usr/local/apache2/htdocs/


    webserver02:
        image: webserver02:latest
        container_name: webserver02
        build: ./web/.
        volumes:
          - ./user02/html:/usr/local/apache2/htdocs/
          - ./user02/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
          - 30002:80

    appserver02:
        image: appserver02:latest
        container_name: appserver02
        build: ./app/.
        depends_on:
          - webserver02
        environment:
          ctf_flag: juegoctf{nicelist_37323}
          key: 37323
        volumes:
          - ./user02/html:/usr/local/apache2/htdocs/


    webserver03:
        image: webserver03:latest
        container_name: webserver03
        build: ./web/.
        volumes:
          - ./user03/html:/usr/local/apache2/htdocs/
          - ./user03/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
          - 30003:80

    appserver03:
        image: appserver03:latest
        container_name: appserver03
        build: ./app/.
        depends_on:
          - webserver03
        environment:
          ctf_flag: juegoctf{nicelist_16199}
          key: 16199
        volumes:
          - ./user03/html:/usr/local/apache2/htdocs/


